version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependabot
      - actions
    schedule:
      interval: weekly
    commit-message:
      prefix: 'chore(deps): update actions/'

  - package-ecosystem: npm
    directory: /
    labels:
      - dependabot
      - npm
    schedule:
      interval: weekly
    commit-message:
      prefix: 'chore(deps): update npm/'
